
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author future
 */
public class JFr_Bill_F5 extends javax.swing.JFrame {

    /**
     * Creates new form Frame7
     */
    public JFr_Bill_F5() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        /////////////////////
        JFr_Data_F2 fram2 = new JFr_Data_F2();
        JFr_Hotel_F3 fram3 = new JFr_Hotel_F3();
        JFr_Resturant_F4 f9 = new JFr_Resturant_F4();
        //////////////////////

        /////////////////////
        jTextFNamecon.setText(fram2.Fnam + " " + fram2.lnam);
        jTextFIDco.setText(fram2.NID);
        jTextFPhoneco1.setText(fram2.phone);
        jTextFCountrycon.setText(fram2.country);
        jTextGEcon.setText(fram2.gender);
        jTextFCitycon.setText(fram3.City2);
        jTextFHotelcon.setText(fram3.hotel_name);
        jTextFRoomcon.setText(fram3.R_name);
        jTextFNDaycon.setText(fram3.num_of_day);
        jTextdateHo.setText(fram3.date_HOT);
        jTextFRestaurantcon1.setText(f9.rest_name);
        jTextdateR.setText(f9.date_RE);
        String s = fram3.num_of_day;
        String d = fram3.price;
        double D_price = Double.parseDouble(d);
        int i_NODay = Integer.parseInt(s);
        double t_price = (i_NODay * D_price) + (i_NODay * D_price * 0.2);
        String total = t_price + "";
        jTotal.setText(total);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFIDco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFNDaycon = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFCountrycon = new javax.swing.JTextField();
        jTextGEcon = new javax.swing.JTextField();
        jTextFRoomcon = new javax.swing.JTextField();
        jTextFNamecon = new javax.swing.JTextField();
        jTextFCitycon = new javax.swing.JTextField();
        jTextFHotelcon = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTextdateHo = new javax.swing.JTextField();
        jTextdateR = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTotal = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextFRestaurantcon1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextFPhoneco1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("jLabel2");

        jRadioButton2.setText("Female");

        jLabel4.setText("Name");

        jLabel5.setText("Phone");

        jLabel6.setText("Country");

        jRadioButton1.setText("Male");

        jTextField1.setText("jTextField1");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Please confirm your rigesteration:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 610, 41));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("Country:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 90, 30));

        jTextFIDco.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFIDco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFIDco.setEnabled(false);
        jTextFIDco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFIDcoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFIDco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 310, 30));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 176, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 204));
        jLabel9.setText("Name:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 204));
        jLabel10.setText("ID:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 80, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 204));
        jLabel11.setText("Hotel:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 80, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 204));
        jLabel14.setText("Number of days:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 160, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 255, 204));
        jLabel15.setText("The date of the Restaurant reservation:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 360, 30));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/forward.png"))); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 750, 140, 40));

        jTextFNDaycon.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFNDaycon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFNDaycon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFNDaycon.setEnabled(false);
        jTextFNDaycon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFNDayconActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFNDaycon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 50, 30));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/updating-arrows.png"))); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 750, 132, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 204));
        jLabel12.setText("City:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 80, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 204));
        jLabel13.setText("Room of Hoteal:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 160, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 255, 204));
        jLabel17.setText("Gender:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 80, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 255, 204));
        jLabel18.setText("The date of the hotel reservation:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 320, 30));

        jTextFCountrycon.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFCountrycon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFCountrycon.setEnabled(false);
        jTextFCountrycon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFCountryconActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFCountrycon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 310, 30));

        jTextGEcon.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextGEcon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextGEcon.setEnabled(false);
        jTextGEcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGEconActionPerformed(evt);
            }
        });
        getContentPane().add(jTextGEcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 310, 30));

        jTextFRoomcon.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFRoomcon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFRoomcon.setEnabled(false);
        jTextFRoomcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFRoomconActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFRoomcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 300, 30));

        jTextFNamecon.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFNamecon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFNamecon.setEnabled(false);
        jTextFNamecon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFNameconActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFNamecon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 310, 30));

        jTextFCitycon.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFCitycon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFCitycon.setEnabled(false);
        jTextFCitycon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFCityconActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFCitycon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 310, 30));

        jTextFHotelcon.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFHotelcon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFHotelcon.setEnabled(false);
        jTextFHotelcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFHotelconActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFHotelcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 310, 30));

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/reply.png"))); // NOI18N
        jButton4.setText(" Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 750, 120, 40));

        jTextdateHo.setBackground(new java.awt.Color(240, 240, 240));
        jTextdateHo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextdateHo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextdateHo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextdateHo.setEnabled(false);
        jTextdateHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextdateHoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextdateHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 200, 30));

        jTextdateR.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextdateR.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextdateR.setEnabled(false);
        jTextdateR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextdateRActionPerformed(evt);
            }
        });
        getContentPane().add(jTextdateR, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 650, 300, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 255, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(" $");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 650, -1, 30));

        jTotal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTotal.setEnabled(false);
        jTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalActionPerformed(evt);
            }
        });
        getContentPane().add(jTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 650, 100, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 255, 204));
        jLabel22.setText("Restaurant:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 110, 30));

        jTextFRestaurantcon1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFRestaurantcon1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFRestaurantcon1.setEnabled(false);
        jTextFRestaurantcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFRestaurantcon1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFRestaurantcon1,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 270, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 255, 204));
        jLabel27.setText("Total Price:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 650, -1, 30));

        jTextFPhoneco1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFPhoneco1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFPhoneco1.setEnabled(false);
        jTextFPhoneco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFPhoneco1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFPhoneco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 310, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 255, 204));
        jLabel19.setText("Phone:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Screenshot (58).png"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 1080, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(this, "Your confirmation has been approved");
        this.setVisible(false);
        JFr_Report_F6 fr = new JFr_Report_F6();
        fr.setVisible(true);
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        JFr_Data_F2 f2 = new JFr_Data_F2();
        f2.setVisible(true);
    }// GEN-LAST:event_jButton3ActionPerformed

    private void jTextFIDcoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFIDcoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFIDcoActionPerformed

    private void jTextFCountryconActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFCountryconActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFCountryconActionPerformed

    private void jTextGEconActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextGEconActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextGEconActionPerformed

    private void jTextFRoomconActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFRoomconActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFRoomconActionPerformed

    private void jTextFNameconActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFNameconActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFNameconActionPerformed

    private void jTextFCityconActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFCityconActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFCityconActionPerformed

    private void jTextFHotelconActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFHotelconActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFHotelconActionPerformed

    private void jTextFNDayconActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFNDayconActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFNDayconActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        next_of_frame_3 f2 = new next_of_frame_3();
        f2.setVisible(true);
    }// GEN-LAST:event_jButton4ActionPerformed

    private void jTextdateHoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextdateHoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextdateHoActionPerformed

    private void jTextdateRActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextdateRActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextdateRActionPerformed

    private void jTotalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTotalActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTotalActionPerformed

    private void jTextFRestaurantcon1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFRestaurantcon1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFRestaurantcon1ActionPerformed

    private void jTextFPhoneco1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFPhoneco1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFPhoneco1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFr_Bill_F5.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFr_Bill_F5.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFr_Bill_F5.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFr_Bill_F5.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFr_Bill_F5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    public static javax.swing.JTextField jTextFCitycon;
    public static javax.swing.JTextField jTextFCountrycon;
    public static javax.swing.JTextField jTextFHotelcon;
    public static javax.swing.JTextField jTextFIDco;
    public static javax.swing.JTextField jTextFNDaycon;
    public static javax.swing.JTextField jTextFNamecon;
    public static javax.swing.JTextField jTextFPhoneco1;
    public static javax.swing.JTextField jTextFRestaurantcon1;
    public static javax.swing.JTextField jTextFRoomcon;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField jTextGEcon;
    public static javax.swing.JTextField jTextdateHo;
    public static javax.swing.JTextField jTextdateR;
    public static javax.swing.JTextField jTotal;
    // End of variables declaration//GEN-END:variables
}
