
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author future
 */
public class JFr_Hotel_F3 extends javax.swing.JFrame {

    /**
     * Creates new form Frame3
     */
    public JFr_Hotel_F3() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        //////////////////////////
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehla", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from tourist_cities");
            DefaultTableModel dm = new DefaultTableModel();
            ResultSet set = stmt.executeQuery();
            dm.addColumn("Available places");
            while (set.next()) {
                String[] r = {set.getString(1)};
                dm.addRow(r);
            }
            jTableCity.setModel(dm);
        } catch (SQLException ex) {
            System.out.println("Error " + ex);
        }

    }
    public static String City2;
    public static String hotel_name;
    public static String date_HOT;
    public static String num_of_day;
    public static String R_name;
    public static String price;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollBar1 = new javax.swing.JScrollBar();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCity = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableRoom = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextNdayofHotel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableHotel = new javax.swing.JTable();
        jTextFyearofdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextdayofdate = new javax.swing.JTextField();
        jTextFmonthofdate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alexandria", "Luxor", "Aswan", "Hurghada", "Giza" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Ok");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableCity.setBackground(new java.awt.Color(204, 255, 204));
        jTableCity.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTableCity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Available places"
            }
        ));
        jTableCity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableCity.setRowHeight(30);
        jTableCity.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jTableCity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCityMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCity);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 250, 150));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/forward.png"))); // NOI18N
        jButton2.setText("continue ");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 750, 153, 40));

        jTableRoom.setBackground(new java.awt.Color(204, 255, 204));
        jTableRoom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableRoom.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTableRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Available Rooms", "Number of beds", "The view", "price"
            }
        ));
        jTableRoom.setGridColor(new java.awt.Color(102, 102, 102));
        jTableRoom.setRowHeight(30);
        jTableRoom.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jTableRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRoomMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableRoom);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 990, 150));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Please Choose and Select your The Hotel: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 520, 38));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("Please Choose and Select your Destination: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 520, 38));

        jTextNdayofHotel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextNdayofHotel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextNdayofHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNdayofHotelActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNdayofHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, 80, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("Enter the number of days:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 190, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("Please Choose and Select your The Hotel: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 520, 38));

        jTableHotel.setBackground(new java.awt.Color(204, 255, 204));
        jTableHotel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableHotel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTableHotel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hotels", "Rute", "Location", "ID"
            }
        ));
        jTableHotel.setGridColor(new java.awt.Color(102, 102, 102));
        jTableHotel.setRowHeight(30);
        jTableHotel.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jTableHotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHotelMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableHotel);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 990, 150));

        jTextFyearofdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFyearofdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFyearofdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFyearofdateActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFyearofdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 650, 50, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("Enter The Date Of Reservation:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 650, 220, 40));

        jTextdayofdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextdayofdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextdayofdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextdayofdateActionPerformed(evt);
            }
        });
        getContentPane().add(jTextdayofdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 650, 30, 40));

        jTextFmonthofdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFmonthofdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFmonthofdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFmonthofdateActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFmonthofdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 650, 30, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("/");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 650, 20, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("/");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 650, 20, 40));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/reply.png"))); // NOI18N
        jButton3.setText(" Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 750, 120, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Screenshot (58).png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 1080, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTableCityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCityMouseClicked
        // TODO add your handling code here:
        int row_num = jTableCity.getSelectedRow();
        City2 = jTableCity.getValueAt(row_num, 0).toString();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehla", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select hotel_name, hotels_rate, hotels_location, hotel_id from hotel where city =?");
            DefaultTableModel dm = new DefaultTableModel();
            stmt.setString(1, City2);
            ResultSet set = stmt.executeQuery();
            dm.addColumn("Hotels");
            dm.addColumn("Rute");
            dm.addColumn("Location");
            dm.addColumn("ID");
            while (set.next()) {
                String[] r = {set.getString(1), set.getString(2), set.getString(3), set.getString(4)};
                dm.addRow(r);
            }
            jTableHotel.setModel(dm);
        } catch (SQLException ex) {
            System.out.println("Error " + ex);
        }
    }//GEN-LAST:event_jTableCityMouseClicked

    private void jTextNdayofHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNdayofHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNdayofHotelActionPerformed

    private void jTextFyearofdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFyearofdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFyearofdateActionPerformed

    private void jTextdayofdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextdayofdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextdayofdateActionPerformed

    private void jTextFmonthofdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFmonthofdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFmonthofdateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        JFr_Data_F2 f2 = new JFr_Data_F2();
        f2.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //  JFr_Hotel_F3 fram3 = new JFr_Hotel_F3();
        //String s = fram3.num_of_day;
        // String d = fram3.price;

        //   int final_price = Integer.parseInt(s);
        int D_day = Integer.parseInt(jTextdayofdate.getText());
        int D_month = Integer.parseInt(jTextFmonthofdate.getText());
        int D_year = Integer.parseInt(jTextFyearofdate.getText());
        next_of_frame_3 fn3 = new next_of_frame_3();
        String day = jTextdayofdate.getText();
        String mounth = jTextFmonthofdate.getText();
        String year = jTextFyearofdate.getText();
        String dayn = jTextNdayofHotel.getText();
        String gen = "";
        if (day.compareTo(gen) == 0) {
            JOptionPane.showMessageDialog(this, " you shoud write the date of day ! ");
        } else if (mounth.compareTo(gen) == 0) {
            JOptionPane.showMessageDialog(this, " you shoud write the date of month ! ");
        } else if (year.compareTo(gen) == 0) {
            JOptionPane.showMessageDialog(this, " you shoud write the date of year ! ");
        } else if (dayn.compareTo(gen) == 0) {
            JOptionPane.showMessageDialog(this, " you shoud write the number of day ! ");
        } else if (D_day > 31 || D_day < 1) {
            JOptionPane.showMessageDialog(this, " You should review the number on the day of booking ");
        } else if (D_month > 12 || D_month < 1) {
            JOptionPane.showMessageDialog(this, " You should review the reservation month number ");
        } else if (D_year > 2025 || D_year < 2021) {
            JOptionPane.showMessageDialog(this, " You should review the reservation year number ");
        } else {
            date_HOT = jTextFyearofdate.getText() + "-" + jTextFmonthofdate.getText() + "-" + jTextdayofdate.getText();
            num_of_day = jTextNdayofHotel.getText();
            fn3.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTableHotelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHotelMouseClicked
        // TODO add your handling code here:
        int row_num = jTableHotel.getSelectedRow();
        hotel_name = jTableHotel.getValueAt(row_num, 0).toString();
        String id = jTableHotel.getValueAt(row_num, 3).toString();

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehla", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select available_places ,No_beds ,the_vies ,price from aservice where hotel_id =?");
            DefaultTableModel dm = new DefaultTableModel();
            stmt.setString(1, id);
            ResultSet set = stmt.executeQuery();
            dm.addColumn("Available Rooms");
            dm.addColumn("Number of Beds");
            dm.addColumn("The view");
            dm.addColumn("Price");
            while (set.next()) {
                String[] r = {set.getString(1), set.getString(2), set.getString(3), set.getString(4)};
                dm.addRow(r);
            }
            jTableRoom.setModel(dm);
        } catch (SQLException ex) {
            System.out.println("Error " + ex);
        }
    }//GEN-LAST:event_jTableHotelMouseClicked

    private void jTableRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRoomMouseClicked
        // TODO add your handling code here:
        int row_num = jTableRoom.getSelectedRow();
        R_name = jTableRoom.getValueAt(row_num, 0).toString();
        price = jTableRoom.getValueAt(row_num, 3).toString();
    }//GEN-LAST:event_jTableRoomMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFr_Hotel_F3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFr_Hotel_F3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFr_Hotel_F3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFr_Hotel_F3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFr_Hotel_F3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable jTableCity;
    private javax.swing.JTable jTableHotel;
    private javax.swing.JTable jTableRoom;
    private javax.swing.JTextField jTextFmonthofdate;
    private javax.swing.JTextField jTextFyearofdate;
    private javax.swing.JTextField jTextNdayofHotel;
    private javax.swing.JTextField jTextdayofdate;
    // End of variables declaration//GEN-END:variables
}
