
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author future
 */
public class JFr_Resturant_F4 extends javax.swing.JFrame {

    /**
     * Creates new form Frame9
     */
    public JFr_Resturant_F4() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        ////////////////////////////////
        try {
            JFr_Hotel_F3 f3 = new JFr_Hotel_F3();
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rehla", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select rest_name ,rest_rate ,resturants_location from resturant where city =?");
            DefaultTableModel dm = new DefaultTableModel();
            stmt.setString(1, f3.City2);
            ResultSet set = stmt.executeQuery();
            dm.addColumn("Restaurant");
            dm.addColumn("Rate");
            dm.addColumn("Location");
            while (set.next()) {
                String[] r = {set.getString(1), set.getString(2), set.getString(3)};
                dm.addRow(r);
            }
            jTableRestaurant.setModel(dm);
        } catch (SQLException ex) {
            System.out.println("Error " + ex);
        }

    }
    public static String date_RE;
    public static String rest_name;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTableRestaurant = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextHourR = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFMinutesR = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFyearofdateR = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextdayofdateR = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFmonthofdateR = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableRestaurant.setBackground(new java.awt.Color(204, 255, 204));
        jTableRestaurant.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableRestaurant.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTableRestaurant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Restaurant", "Rute", "Location"
            }
        ));
        jTableRestaurant.setGridColor(new java.awt.Color(102, 102, 102));
        jTableRestaurant.setRowHeight(40);
        jTableRestaurant.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jTableRestaurant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRestaurantMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableRestaurant);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 990, 240));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("Please Choose and Select your Restaurant: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 520, 38));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("Enter The Time Of Reservation:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, 220, 40));

        jTextHourR.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextHourR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextHourR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHourRActionPerformed(evt);
            }
        });
        getContentPane().add(jTextHourR, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 30, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(":");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 20, 40));

        jTextFMinutesR.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFMinutesR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFMinutesR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFMinutesRActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFMinutesR, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 560, 30, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("/");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 20, 40));

        jTextFyearofdateR.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFyearofdateR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFyearofdateR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFyearofdateRActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFyearofdateR, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 50, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 204));
        jLabel10.setText("Enter The Date Of Reservation:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 220, 40));

        jTextdayofdateR.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextdayofdateR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextdayofdateR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextdayofdateRActionPerformed(evt);
            }
        });
        getContentPane().add(jTextdayofdateR, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 30, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("/");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 20, 40));

        jTextFmonthofdateR.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFmonthofdateR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFmonthofdateR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFmonthofdateRActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFmonthofdateR, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 30, 40));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/forward.png"))); // NOI18N
        jButton2.setText("continue ");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 750, 153, 40));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/reply.png"))); // NOI18N
        jButton3.setText(" Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 750, 120, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Screenshot (58).png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 1080, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextHourRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHourRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHourRActionPerformed

    private void jTextFMinutesRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFMinutesRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFMinutesRActionPerformed

    private void jTextFyearofdateRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFyearofdateRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFyearofdateRActionPerformed

    private void jTextdayofdateRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextdayofdateRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextdayofdateRActionPerformed

    private void jTextFmonthofdateRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFmonthofdateRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFmonthofdateRActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int D_day = Integer.parseInt(jTextdayofdateR.getText());
        int D_month = Integer.parseInt(jTextFmonthofdateR.getText());
        int D_year = Integer.parseInt(jTextFyearofdateR.getText());
        int T_hour = Integer.parseInt(jTextHourR.getText());
        int T_minute = Integer.parseInt(jTextFMinutesR.getText());
        String hour = jTextHourR.getText();
        String minute = jTextFMinutesR.getText();
        String day = jTextdayofdateR.getText();
        String mounth = jTextFmonthofdateR.getText();
        String year = jTextFyearofdateR.getText();
        String gen = "";
        int b = hour.compareTo(gen);
        int a = minute.compareTo(gen);
        int i = day.compareTo(gen);
        int j = mounth.compareTo(gen);
        int x = year.compareTo(gen);
        if (i == 0) {
            JOptionPane.showMessageDialog(this, " you shoud write the date of day ! ");
        } else if (j == 0) {
            JOptionPane.showMessageDialog(this, " you shoud write the date of month ! ");
        } else if (x == 0) {
            JOptionPane.showMessageDialog(this, " you shoud write the date of year ! ");
        } else if (a == 0) {
            JOptionPane.showMessageDialog(this, " you shoud write the minute ! ");
        } else if (b == 0) {
            JOptionPane.showMessageDialog(this, " you shoud write the hour! ");
        } else if (D_day > 31 || D_day < 1) {
            JOptionPane.showMessageDialog(this, " You should review the number on the day of booking !");
        } else if (D_month > 12 || D_month < 1) {
            JOptionPane.showMessageDialog(this, " You should review the reservation month number !");
        } else if (D_year > 2025 || D_year < 2021) {
            JOptionPane.showMessageDialog(this, " You should review the reservation year number !");
        } else if (T_hour > 24 || T_hour < 0) {
            JOptionPane.showMessageDialog(this, " You should review the reservation Hour !");
        } else if (T_minute > 59 || T_minute < 1) {
            JOptionPane.showMessageDialog(this, " You should review the reservation Minute ! ");
        }else {
            JFr_Bill_F5 f2 = new JFr_Bill_F5();
            JFr_Resturant_F4 f9 = new JFr_Resturant_F4();
            this.setVisible(false);
            f2.setVisible(true);
            date_RE = jTextFyearofdateR.getText() + "-" + jTextFmonthofdateR.getText() + "-" + jTextdayofdateR.getText() + " " + jTextHourR.getText() + ":" + jTextFMinutesR.getText();
            f2.jTextdateR.setText(f9.date_RE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        next_of_frame_3 f2 = new next_of_frame_3();
        f2.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTableRestaurantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRestaurantMouseClicked
        // TODO add your handling code here:
        int row_num = jTableRestaurant.getSelectedRow();
        rest_name = jTableRestaurant.getValueAt(row_num, 0).toString();
    }//GEN-LAST:event_jTableRestaurantMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFr_Resturant_F4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFr_Resturant_F4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFr_Resturant_F4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFr_Resturant_F4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFr_Resturant_F4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableRestaurant;
    private javax.swing.JTextField jTextFMinutesR;
    private javax.swing.JTextField jTextFmonthofdateR;
    private javax.swing.JTextField jTextFyearofdateR;
    private javax.swing.JTextField jTextHourR;
    private javax.swing.JTextField jTextdayofdateR;
    // End of variables declaration//GEN-END:variables
}
