
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author future
 */
public class JFr_Data_F2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public JFr_Data_F2() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    public static String Fnam;
    public static String lnam;
    public static String phone;
    public static String country;
    public static String NID;
    public static String gender = "Male";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFNID = new javax.swing.JTextField();
        jTextFPhone = new javax.swing.JTextField();
        jTextFCountry = new javax.swing.JTextField();
        jRadioBMale = new javax.swing.JRadioButton();
        jRadioBFemal = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jTextFNameF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("Name");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 153));
        jButton1.setText("Egyptian");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 613, 96, 33));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/forward.png"))); // NOI18N
        jButton2.setText("Register ");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 750, 148, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Please Enter Your Data: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 260, 26));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("National ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 190, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Phone:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 190, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Country:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 570, 190, 40));

        jTextFNID.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFNID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFNIDActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFNID, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 310, 40));

        jTextFPhone.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 310, 40));

        jTextFCountry.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFCountryActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 610, 310, 40));

        jRadioBMale.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jRadioBMale);
        jRadioBMale.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioBMale.setForeground(new java.awt.Color(255, 255, 255));
        jRadioBMale.setSelected(true);
        jRadioBMale.setText("Male");
        jRadioBMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBMaleActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioBMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 670, -1, -1));

        jRadioBFemal.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jRadioBFemal);
        jRadioBFemal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioBFemal.setForeground(new java.awt.Color(255, 255, 255));
        jRadioBFemal.setText("Female");
        jRadioBFemal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBFemalActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioBFemal, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 670, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/reply.png"))); // NOI18N
        jButton3.setText(" Back");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 750, 120, 40));

        jTextFNameF.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFNameF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFNameFActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFNameF, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 310, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" First Name:");
        jLabel9.setAutoscrolls(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 190, 40));

        jTextFName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 310, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" Last Name:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 190, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Screenshot (51).png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 580, 830));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Screenshot (47).png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 10, 830));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Screenshot (53).png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 10, 830));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Screenshot (47).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 440, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFr_Hotel_F3 f3 = new JFr_Hotel_F3();
        String nameF = jTextFNameF.getText();
        String nameL = jTextFName.getText();
        String nat_id = jTextFNID.getText();
        String phon = jTextFPhone.getText();
        String coun = jTextFCountry.getText();
        String gen = "";
        int f = nameF.compareTo(gen);
        int l = nameL.compareTo(gen);
        int id = nat_id.compareTo(gen);
        int j = phon.compareTo(gen);
        int x = coun.compareTo(gen);
        if (f == 0) {
            JOptionPane.showMessageDialog(this, " you shoud Enter the Firstname ! ");
        } else if (l == 0) {
            JOptionPane.showMessageDialog(this, " you shoud Enter the Lasttname ! ");
        } else if (id == 0) {
            JOptionPane.showMessageDialog(this, " you shoud Enter the National ID ! ");
        } else if (j == 0) {
            JOptionPane.showMessageDialog(this, " you shoud Enter the phone Number ! ");
        } else if (x == 0) {
            JOptionPane.showMessageDialog(this, " you shoud Enter the country ! ");
        } else if (nat_id.length() != 14) {
            JOptionPane.showMessageDialog(this, " you shoud Enter Correct National ID ! ");
        } else if (phon.length() < 10 || phon.length() > 11) {
            JOptionPane.showMessageDialog(this, " you shoud Enter Correct the phone Number ! ");
        } else {
            this.setVisible(false);
            f3.setVisible(true);
            Fnam = jTextFNameF.getText();
            lnam = jTextFName.getText();
            NID = jTextFNID.getText();
            phone = jTextFPhone.getText();
            country = jTextFCountry.getText();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFCountryActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        JFr_Main_F1 f1 = new JFr_Main_F1();
        f1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFPhoneActionPerformed

    private void jTextFNIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFNIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFNIDActionPerformed

    private void jRadioBFemalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBFemalActionPerformed
        // TODO add your handling code here:
        gender = "Female";
    }//GEN-LAST:event_jRadioBFemalActionPerformed

    private void jRadioBMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBMaleActionPerformed
        // TODO add your handling code here:
        gender = "Male";
    }//GEN-LAST:event_jRadioBMaleActionPerformed

    private void jTextFNameFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFNameFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFNameFActionPerformed

    private void jTextFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFr_Data_F2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFr_Data_F2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFr_Data_F2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFr_Data_F2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFr_Data_F2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioBFemal;
    private javax.swing.JRadioButton jRadioBMale;
    private javax.swing.JTextField jTextFCountry;
    private javax.swing.JTextField jTextFNID;
    private javax.swing.JTextField jTextFName;
    private javax.swing.JTextField jTextFNameF;
    private javax.swing.JTextField jTextFPhone;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
